@startuml

class Party <<archetype>> {
{field} <<o>> description: str
{field} name: str
{method} identifier(): PartyIdentifier
{method} registered_identifiers(): RegisteredIdentifier[]
{method} addresses(): Address[]
{method} roles(): PartyRole[]
{method} preferences(): PreferenceList[]
}


class UniqueIdentifier <<archetype>>{
    get(): str
}

class PartyIdentifier <<archetype>>{
    identifier: str
    get(): str
}
class PartySignature <<archetype>>{
when: Datetime
<<o>> reason: str
identifier(): PartyIdentifier
authentication(): PartyAuthentication
}
class PartyAuthentication <<archetype>>{
}
note right of PartyAuthentication
It may be:
* user ID and password combination
* in-house security tokens
* secure digital certificate - VeriSign (www.verisign.com) or Thawte (www.thawte.com)
end note

UniqueIdentifier <|-down- PartyIdentifier

PartyIdentifier "1" <-* "1" PartySignature
PartySignature "1" *--> "1" PartyAuthentication

Party "1..*" -right- "0..*" Address: \t\t

class Address <<archetype>> {
valid_from: Datetime
valid_to: Datetime
address(): str
}

'(Party, Address) .. AddressProperties
'
'class AddressProperties <<archetype>> {
'use: String[1..*]
'}


Party "1" *-up-> "1" PartyIdentifier
Party "1" *-up-> "0..*" PartyAuthentication : <<o>>

'Address -[hidden]up- PartyAuthentication


together {
class Preference <<archetype>>
package {
class PartyRelationshipArchetypePattern <<archetype>>
}
class RegisteredIdentifier <<archetype>>{
identifier: str
<<o>> type: str
valid_from: Datetime
valid_to: Datetime
registration_authority: str
}
note left of RegisteredIdentifier::type
  e.g.
  for Company: VATRegistrationNumber
  for Person: Passport number, Social security number, Identity card number
end note
}


Preference -[hidden]down- PartyRelationshipArchetypePattern
PartyRelationshipArchetypePattern -[hidden]down- RegisteredIdentifier


Party "1" *-left-> "0..*" Preference : <<o>>
Party .left.> PartyRelationshipArchetypePattern
Party <.left. PartyRelationshipArchetypePattern
RegisteredIdentifier "1" *-up-> "0..*" Party : <<o>>

Preference -[hidden]down- PartyRelationshipArchetypePattern

together {
class Organization <<archetype>>
class OrganizationName <<archetype>>
}
Organization "1" *-down-> "1" OrganizationName
Organization "1" *-down-> "0..*" OrganizationName : <<o>> otherOrganizationNames

Party <|-down- Organization

together {
class Person <<archetype>>
class PersonName <<archetype>>
}
Person "1" *-down-> "1" PersonName
Person "1" *-down-> "0..*" PersonName : <<o>> otherPersonNames

Party <|-down- Person

@enduml
